# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gallenmar
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-testing
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-testing

provider:
  name: aws
  runtime: nodejs22.x
  environment:
    DB_URL: ${env:DB_URL}
    DB_KEY: ${env:DB_KEY}

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
